### PR TITLE
Add ssh configuration to Vagrantfile template

### PR DESCRIPTION
**Pull request by lanahra**

### CODE REVIEW

**Comment by edin-m** [comment]
Can you fix two failing tests? The 'after all' failing hook is not related to this PR, I'll look into that.

**Comment by lanahra** [comment]
I'll take a look.

**Comment by lanahra** [comment]
The template generation tests unfortunately only remove \n\r when comparing the outputs, so the Vagrantfile to be compared to must have the right amount of "two spaces", that are introduced into the generated Vagrantfile because of all the indentation on all the template tags.

Removing the indentation from the template tags I introduced solves the problem, but makes the template file inconsistent to the eyes. This can be solved be either removing the indentation from all the template tags (the method I prefer) or adding "two spaces" to both example1.Vagrantfile and example2.Vagrantfile and keeping the indentation even on all template tags.

Another thing that I tried to do is to remove the blank lines generated by the template, but I didn't find a way to do that yet.

**Comment by edin-m** [comment]
Good enough for me. Other work can be done separately as a refactor. I'll merge this if you don't have any more updates planned?

**Comment by lanahra** [comment]
That's all from me on this topic, maybe in the future I'll add support for the other configuration options in another pull request.

Thank you very much for your attention :)

**Comment by edin-m** [comment]
Sure thing, thank you for contributing!

**Pull request merged**
